travis:
  secure:
    BINSTAR_TOKEN: Uv2KSEeH1S0Z/kNYzuajPG72EJ+hh+LjcMQS1k+CfPEaY9ZvDtzYMTqNOmePR+T8FUlsb+JIQ94edYVwzQhpsIDJRvTMz7b0pZCzNWAGJHrigQEQKISquxLVRMib9WCxVS/aFO12ja1PSI76smfpUaUn90IbmZ66q0+ORBlwrtBY8Fux2H6pQH4DTP1mSnP4r+hoZH6u2ulg3ic4bDfFOrRGp1L/h45fNL7m7Riwif4ytnY7Ad9T3fxV2EB3A5Uq5PTVfpYBYi4HwvNBvuReiK1IM6UwibGcwKUiRwmTNVecCYEUbNJ8iMFf7k9So1wlXMSJVTdm8760bxG11M29M6TX1hqMo6J5gW9L7eBw5ru1H6tHNS51hkBvMXwu20u0NdkdfIJDypFszGfP9zvj7FOiSTHFTI0WLUmalF6ERW468Hqe4vQRMWDnUbUeJe4TdbhMljs6h7Bl/SDyFRpj+38CPUSxP9RMyJhBua5t3DK5sKGjmnRgpbgyFwx1m7cMbeY5T530xllHs2GvUU+2m5M8fTR6fTR5Z2a6IvB6ZWnhTuimS4efY7eZ7SFg2Zgu7rKItVszIat/e1jbnyVU84s5GWodInpRdU6Ia+8FviCdzXmqaukDqXSw9l6bhFXg2/wWjxa6j6zA2ayMeuOjXxkGbpPR0Mp6kmLxiFsO4KQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
